### ISSUE TITLE
Android Developer - Ho Chi Minh - Full time - Remote - from 500$

### ISSUE THREAD

**Issue by hien1dreamm** [1dreamm/jobs_board#3]
## About us - 1dreamm
We are a young startup team from Vietnam working on mobile and web development. As part of our effort to drive Vietnam forward, we are looking for a young talented Android developer working full time at Ho Chi Minh city.

## Location
* Remote (working online)
* We have an office at Binh Thanh district HCM city, you can work there if you like to

## Time
* Fulltime
* From 9am to 18pm (break at 12h30 to 13h30)

## Requirements
* Good knowledge on java programming language
* Good experience in mobile development
* Experience with git, github, bitbucket
* Not require but prefer developers with experience in Android developing

## You’ll be responsible for
* Building and maintain our android apps
* Work in the team to develop our products

## Benefit
* Salary from 500$ / month (depends on your experience)
* 13th month salary
* Review salary and bonus every 6 months
* We are a startup so you will become a member of our core team
* Free lunch

## Contact
* Email: bot@1dreamm.com

## In your CV
* Please include some projects that you have participated in and how did you contribute to these projects.
* Your expected salary

**Comment by bqthuan** [comment]
I have been developing Android app for three years.
Currently, i am working for a company, let me know if you can offer me a slot with working hours from 20pm

**Comment by hien1dreamm** [comment]
@bqthuan please send your CV to the email address above, we will consider whether you are suitable for the job.

**Comment by chuoichien** [comment]
I'm a software developer with 5-6 years of experience, Senior Software Engineer in ZaloGroup, i have been developing Android, PHP, J2EE, Heroku, Windows Phone. Can i work part-time?

**Comment by le-dong** [comment]
@hien1dreamm I'm an android developer, I have 3 months experience, i can work full time.

**Comment by IHNEL** [comment]
Hi, 
I am freelancer with more than 6 years experience in Android Development. I am interested in the job and hope we can work together.
This is my CV: http://nmbinh.tk

Thanks.
