### ISSUE TITLE
QA - Tester - Ho Chi Minh - Full time

### ISSUE THREAD

**Issue by hien1dreamm** [1dreamm/jobs_board#4]
## About us - 1dreamm
We are a young startup team from Vietnam working on mobile and web development. As part of our effort to drive Vietnam forward, we are looking for a young talented Quality Assurance (as known as QA or Tester) working full time at Ho Chi Minh city.

## Location
* Binh Thanh, HCM, Vietnam

## Time
* Part time
* From 9am to 18pm (break at 12h30 to 13h30)

## Requirements
* Good knowledge on software development and software life circle
* Have experience with mobile or web development
* Not require but prefer engineers with experience in QA

## You’ll be responsible for
* Testing weekly mobile apps or web for our products
* Work with the development team to help build the best quality product
* Writing some scripts for automation tests

## Benefit
* Competitive salary
* 13th month salary
* Review salary and bonus every 6 months
* We are a startup so you will become a member of our core team

## Contact
* 1dreamm email - bot@1dreamm.com

## In your CV
* Please explain why you like this job
* Your expected salary

**Comment by ThamNgoNgoc** [comment]
I wants to do this job.

**Comment by ThamNgoNgoc** [comment]
Email to me:  nntham@yahoo.com. Thanks
